# Layer configuration for meta-omelet
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-omelet"
BBFILE_PATTERN_meta-omelet = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-omelet = "10"

LAYERDEPENDS_meta-omelet = "core raspberrypi"
LAYERSERIES_COMPAT_meta-omelet = "scarthgap"
