# Layer configuration for meta-omelet
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-omelet"
BBFILE_PATTERN_meta-omelet = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-omelet = "10"

# networking-layer = meta-networking, provides NetworkManager (WiFi control).
LAYERDEPENDS_meta-omelet = "core raspberrypi networking-layer"
LAYERSERIES_COMPAT_meta-omelet = "scarthgap"
